import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - the server build is generated by `remix vite:build`
import * as build from "../build/server";

const remixHandler = createPagesFunctionHandler({ build });

// Webflow Cloud mounts the app at a path prefix (e.g. /vite-remix-cf).
// The Remix basename is set from process.env.COSMIC_MOUNT_PATH at build
// time; if that env var is not available when the builder runs, Remix
// builds with basename "/" and will not match prefixed URLs. This
// wrapper strips everything before /api/ so API routes resolve even
// when the mount prefix was not baked into the build.
export const onRequest: PagesFunction = (context) => {
  const url = new URL(context.request.url);
  const apiIndex = url.pathname.indexOf("/api/");
  if (apiIndex > 0) {
    url.pathname = url.pathname.slice(apiIndex);
    const rewrittenRequest = new Request(url.toString(), context.request);
    return remixHandler({ ...context, request: rewrittenRequest });
  }
  return remixHandler(context);
};
