/// <reference types="@cloudflare/workers-types" />

import { createRequestHandler, type ServerBuild } from "@remix-run/cloudflare";
// @ts-ignore - the server build is generated by `remix vite:build`
import * as build from "./build/server";

export interface Env {
  DB: D1Database;
  SESSIONS: KVNamespace;
  FLAGS: KVNamespace;
  MEDIA: R2Bucket;
  ASSETS: Fetcher;
}

const handleRemixRequest = createRequestHandler(build as unknown as ServerBuild);

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // Route API paths straight to Remix. Passing through env.ASSETS would
    // consume the request body (ReadableStream is disturbed), breaking POST
    // actions. Static assets can't live under /api/* anyway. The URL is
    // passed through untouched so Remix's configured basename (set from
    // COSMIC_MOUNT_PATH at build time) can match prefixed routes.
    const url = new URL(request.url);
    const isApi = url.pathname.includes("/api/");
    if (!isApi) {
      const asset = await env.ASSETS.fetch(request);
      if (asset.status !== 404) return asset;
    }

    return handleRemixRequest(request, {
      cloudflare: { env, ctx },
    } as unknown as AppLoadContext);
  },
};

type AppLoadContext = {
  cloudflare: { env: Env; ctx: ExecutionContext };
};
